import createClient from "openapi-fetch";

import type { paths } from "./openapi"; // generated by openapi-typescript

const strapiEndpoint = import.meta.env.VITE_STRAPI_URL;

export default createClient<paths>({ baseUrl: `${strapiEndpoint}/api` });
