import createClient from "openapi-fetch";
import qs from "qs";

import type { paths } from "./openapi"; // generated by openapi-typescript

const strapiEndpoint = import.meta.env.VITE_STRAPI_URL;

export default createClient<paths>({
  baseUrl: `${strapiEndpoint}/api`,
  querySerializer: qs.stringify,
});
