import createClient from "openapi-fetch";
import qs from "qs";

import type { paths } from "./openapi"; // generated by openapi-typescript

const strapiEndpoint = import.meta.env.VITE_STRAPI_URL;

export type Paths = paths;

const client = createClient<Paths>({
  baseUrl: `${strapiEndpoint}/api`,
  querySerializer: qs.stringify,
});

// client.use({
//   onRequest({ request }) {
//     console.log("Request:", request.method, request.url);
//   },
// });

export default client;
